
spring:
  application:
    group: studies
    name: studies-java
    datasource:
      driver: org.h2.Driver
      url: jdbc:h2:mem:testdb;
      username: test
      password: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    port: 8080
    contextPath: /${spring.application.name}

feature:
  swagger: true